/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.rj.macae.femass.dsi.cookbook.gui;

import br.rj.macae.femass.dsi.cookbook.controle.ClienteControle;
import br.rj.macae.femass.dsi.cookbook.jpa.ClienteE;
import br.rj.macae.femass.dsi.cookbook.modelo.Cliente;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hellk
 */
public class GuiCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form GuiCliente
     */
    public GuiCliente() throws SQLException {
        initComponents();
        limparCampos();
        bloquearCampos();
        carregarLista();
        buttonStartSet();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtDependentes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        btmSalvar = new javax.swing.JButton();
        btmCancelar = new javax.swing.JButton();
        btmNovo = new javax.swing.JButton();
        btmEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Nome");

        jLabel2.setText("e-mail");

        jLabel3.setText("Telefone");

        jLabel4.setText("Dependentes");

        jLabel6.setText("Clientes");

        txtNome.setText("jTextField1");

        txtEndereco.setText("jTextField2");

        txtTelefone.setText("jTextField3");

        txtDependentes.setText("jTextField4");
        txtDependentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDependentesActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Quarto", "ID", "Nome", "Telefone", "E-Mail", "Dependentes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.Long.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.setColumnSelectionAllowed(true);
        jScrollPane2.setViewportView(tblClientes);
        tblClientes.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btmSalvar.setText("Salvar");
        btmSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSalvarActionPerformed(evt);
            }
        });

        btmCancelar.setText("Cancelar");
        btmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCancelarActionPerformed(evt);
            }
        });

        btmNovo.setText("Novo");
        btmNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmNovoActionPerformed(evt);
            }
        });

        btmEditar.setText("Editar");
        btmEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmEditarActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText("ID");

        txtID.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDependentes))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEndereco))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(txtTelefone))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btmSalvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmNovo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btmEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtID)
                                    .addComponent(txtNome))))
                        .addContainerGap())
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(0, 408, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmSalvar)
                    .addComponent(btmCancelar)
                    .addComponent(btmNovo)
                    .addComponent(btmEditar)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDependentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDependentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDependentesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btmSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSalvarActionPerformed
        // TODO add your handling code here:
        ClienteControle controle = new ClienteControle();
        try {
            ClienteE c = new ClienteE();
            
            c.setDependentes(Integer.parseInt(txtDependentes.getText()));
            c.setNome(txtNome.getText());
            c.setEndereco(txtEndereco.getText());
            c.setTelefone(txtTelefone.getText());
            
            c.setId(txtID.getText().equals("")? null:Long.parseLong(txtID.getText()));
        
            controle.gravar(c);
        } catch (SQLException ex) {
            Logger.getLogger(GuiCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
           
        try {
            carregarLista();
        } catch (SQLException ex) {
            Logger.getLogger(GuiCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        buttonStartSet();
        bloquearCampos();
        
    }//GEN-LAST:event_btmSalvarActionPerformed

    private void btmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCancelarActionPerformed
        try {
            // TODO add your handling code here:
            carregarLista();
        } catch (SQLException ex) {
            Logger.getLogger(GuiCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
        buttonStartSet();
        bloquearCampos();
    }//GEN-LAST:event_btmCancelarActionPerformed

    private void btmNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmNovoActionPerformed
        // TODO add your handling code here:
        limparCampos();
        liberarCampos();
        btmEditSet();
        
        
    }//GEN-LAST:event_btmNovoActionPerformed

    private void btmEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmEditarActionPerformed
        // TODO add your handling code here:
        if(tblClientes.getSelectedRowCount()>0){
            limparCampos();
                liberarCampos();
            ClienteControle controle = new ClienteControle();
            Long v = (Long) ((DefaultTableModel) tblClientes.getModel()).getValueAt(tblClientes.getSelectedRow(), 1);
            
            try {
                
                ClienteE c;
                c = controle.getCategoriaPorId(v);
                
                txtDependentes.setText(c.getDependentes().toString());
                txtEndereco.setText(c.getEndereco());
                txtID.setText(c.getId().toString());
                txtNome.setText(c.getNome());
                txtTelefone.setText(c.getTelefone());
                
                liberarCampos();
            } catch (SQLException ex) {
                Logger.getLogger(GuiCliente.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            btmEditSet();
        }
    }//GEN-LAST:event_btmEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmCancelar;
    private javax.swing.JButton btmEditar;
    private javax.swing.JButton btmNovo;
    private javax.swing.JButton btmSalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtDependentes;
    private javax.swing.JTextField txtEndereco;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

    private void bloquearCampos() {
    txtDependentes.setEnabled(false); 
    txtEndereco.setEnabled(false);
    txtID.setEnabled(false);
    txtNome.setEnabled(false);
    txtTelefone.setEnabled(false);
    
    }

    private void limparCampos() {
    
        txtDependentes.setText("");
        txtEndereco.setText("");
        txtID.setText("");
        txtNome.setText("");
        txtTelefone.setText("");
     
    }

    private void carregarLista() throws SQLException {
     ClienteControle controle = new ClienteControle();
    
     try{
         controle.atualizarLista(tblClientes);
         
     }catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }         
}

    private void buttonStartSet() {
        
        btmCancelar.setEnabled(false);
        btmEditar.setEnabled(true);
        btmNovo.setEnabled(true);
        btmSalvar.setEnabled(false);
        
    }

    private void liberarCampos() {
     txtDependentes.setEnabled(true); 
    txtEndereco.setEnabled(true);
    txtID.setEnabled(true);
    txtNome.setEnabled(true);
    txtTelefone.setEnabled(true);}

    private void btmEditSet() {
     
        btmCancelar.setEnabled(true);
        btmEditar.setEnabled(false);
        btmNovo.setEnabled(false);
        btmSalvar.setEnabled(true);
    }
}
