/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.rj.macae.femass.dsi.cookbook.gui;

import br.rj.macae.femass.dsi.cookbook.controle.PedidoControle;
import br.rj.macae.femass.dsi.cookbook.controle.QuartoControle;
import br.rj.macae.femass.dsi.cookbook.controle.ReceitaControle;
import br.rj.macae.femass.dsi.cookbook.jpa.PedidoE;
import br.rj.macae.femass.dsi.cookbook.jpa.QuartoE;
import br.rj.macae.femass.dsi.cookbook.jpa.ReceitaE;
import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hellk
 */
public class GuiPedido extends javax.swing.JInternalFrame {

    /**
     * Creates new form guiPedido
     */
    public GuiPedido() throws SQLException {
        initComponents();
        StartSet();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReceitas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btmAddReceita = new javax.swing.JButton();
        btmRemoveReceita = new javax.swing.JButton();
        btmSalvar = new javax.swing.JButton();
        btmCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtOrigem = new javax.swing.JTextField();
        txtDestino = new javax.swing.JTextField();
        cbbcliente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        cbbPedidos = new javax.swing.JComboBox<>();
        btmNovo = new javax.swing.JButton();
        btmAlterar = new javax.swing.JButton();
        btmRemover = new javax.swing.JButton();
        btmSair = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbbCategoria = new javax.swing.JComboBox<>();
        cbbReceita = new javax.swing.JComboBox<>();

        jLabel1.setText("Numero");

        jLabel2.setText("Origem");

        jLabel3.setText("Pedido");

        tblReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Numero", "Nome", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Long.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReceitas.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblReceitas);
        tblReceitas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        jLabel4.setText("Cliente");

        btmAddReceita.setText("+");
        btmAddReceita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAddReceitaActionPerformed(evt);
            }
        });

        btmRemoveReceita.setText("-");

        btmSalvar.setText("Salvar");

        btmCancelar.setText("Cancelar");
        btmCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Destino");

        txtNumero.setText("jTextField1");

        txtOrigem.setText("jTextField2");

        txtDestino.setText("jTextField3");

        cbbcliente.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbclienteItemStateChanged(evt);
            }
        });

        jLabel6.setText("Pedidos");

        cbbPedidos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbPedidosItemStateChanged(evt);
            }
        });

        btmNovo.setText("Novo");
        btmNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmNovoActionPerformed(evt);
            }
        });

        btmAlterar.setText("Alterar");
        btmAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmAlterarActionPerformed(evt);
            }
        });

        btmRemover.setText("Remover");
        btmRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmRemoverActionPerformed(evt);
            }
        });

        btmSair.setText("Sair");
        btmSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmSairActionPerformed(evt);
            }
        });

        jLabel7.setText("Categoria");

        jLabel8.setText("Receita");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbbPedidos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btmNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btmRemover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btmSair))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbcliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btmAddReceita)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btmRemoveReceita)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btmSalvar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btmCancelar)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbReceita, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbCategoria, 0, 338, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtOrigem))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDestino)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbbReceita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmAddReceita)
                    .addComponent(btmRemoveReceita)
                    .addComponent(btmSalvar)
                    .addComponent(btmCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbbcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btmNovo)
                    .addComponent(btmAlterar)
                    .addComponent(btmRemover)
                    .addComponent(btmSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmSairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btmSairActionPerformed

    private void btmAddReceitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAddReceitaActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_btmAddReceitaActionPerformed

    private void btmNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmNovoActionPerformed
        // TODO add your handling code here:
        limparCampos();
        habilitarCampos();
        
        try {
            cbbCategoria.setEnabled(true);
            listarCbbCategoria();
        } catch (SQLException ex) {
            Logger.getLogger(GuiPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        tblReceitas.removeAll();
        btmEditSet();
        btmRemover.setEnabled(false);
    }//GEN-LAST:event_btmNovoActionPerformed

    private void btmAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmAlterarActionPerformed
        // TODO add your handling code here:
        
        ReceitaControle controle = new ReceitaControle();
        limparCampos();
        habilitarCampos();
        try {
            listarCbbCategoria();
        } catch (SQLException ex) {
            Logger.getLogger(GuiPedido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        PedidoE p = (PedidoE) cbbPedidos.getSelectedItem();
        String title = p.getOrigem().getId().toString();
        txtDestino.setText(p.getEndereco());
        txtNumero.setText(p.getId().toString());
        txtOrigem.setText(title);
        listarReceitasPedido(p.getPedido());
        
        btmEditSet();
        
        
    }//GEN-LAST:event_btmAlterarActionPerformed

    private void btmRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmRemoverActionPerformed
        // TODO add your handling code here:
        
        if(cbbPedidos.getSelectedIndex()>=0){
            PedidoControle controle =  new PedidoControle();
            try {
                PedidoE p = controle.getCategoriaPorId(Long.parseLong(txtNumero.getText()));
                controle.excluir(p);
                listarCbbCategoria();
                desabilitarCampos();
                
            } catch (SQLException ex) {
                Logger.getLogger(GuiPedido.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
    }//GEN-LAST:event_btmRemoverActionPerformed

    private void cbbclienteItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbclienteItemStateChanged
        // TODO add your handling code here:
        limparCampos();
        QuartoE q = (QuartoE) cbbcliente.getSelectedItem();
        listarCbbPedido(q.getPedidos());
        cbbPedidos.setEnabled(true);
        btmQuartoSelecionadoSet();
        
    }//GEN-LAST:event_cbbclienteItemStateChanged

    private void cbbPedidosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbPedidosItemStateChanged
        // TODO add your handling code here:
        limparCampos();
        btmPedidoSelecionadoSet();
        
    }//GEN-LAST:event_cbbPedidosItemStateChanged

    private void btmCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmCancelarActionPerformed
        // TODO add your handling code here:
        limparCampos();
        btmStartSet();
        desabilitarCbbsReceitas();
    }//GEN-LAST:event_btmCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmAddReceita;
    private javax.swing.JButton btmAlterar;
    private javax.swing.JButton btmCancelar;
    private javax.swing.JButton btmNovo;
    private javax.swing.JButton btmRemoveReceita;
    private javax.swing.JButton btmRemover;
    private javax.swing.JButton btmSair;
    private javax.swing.JButton btmSalvar;
    private javax.swing.JComboBox<Object> cbbCategoria;
    private javax.swing.JComboBox<Object> cbbPedidos;
    private javax.swing.JComboBox<Object> cbbReceita;
    private javax.swing.JComboBox<Object> cbbcliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblReceitas;
    private javax.swing.JTextField txtDestino;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtOrigem;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void habilitarCampos() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void listarCbbCategoria() throws SQLException {
     ReceitaControle controle = new ReceitaControle();
        List categorias = controle.listarCategorias();
        cbbCategoria.removeAllItems();
        for(Object o:categorias){
            cbbCategoria.addItem(o);
        }
    
    }

    private void listarCbbPedido(List<PedidoE> pedidos) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void listarCbbQuartos() throws SQLException {
    QuartoControle controle = new QuartoControle();
        List categorias = controle.listarQuartosCbb();
        cbbcliente.removeAllItems();
        for(Object o:categorias){
            cbbCategoria.addItem(o);
        }
    }

    private void listarReceitasPedido(List<ReceitaE> pedido) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void btmEditSet() {
        btmAlterar.setEnabled(false);
        btmCancelar.setEnabled(true);
        btmNovo.setEnabled(false);
        btmRemover.setEnabled(true);
        btmSalvar.setEnabled(true);
    }

    private void desabilitarCampos() {
    txtDestino.setEnabled(false);
    txtNumero.setEnabled(false);
    txtOrigem.setEnabled(false);
    desabilitarCbbsReceitas();
    cbbPedidos.setEnabled(false);
    
    }

    private void btmPedidoSelecionadoSet() {
        btmAlterar.setEnabled(true);
        btmCancelar.setEnabled(false);
        btmNovo.setEnabled(true);
        btmRemover.setEnabled(true);
        btmSalvar.setEnabled(false);
    
    }

    private void btmQuartoSelecionadoSet() {
     btmAlterar.setEnabled(false);
     btmCancelar.setEnabled(false);
     btmNovo.setEnabled(true);
     btmRemover.setEnabled(false);
     btmSalvar.setEnabled(false);
    }

    private void desabilitarCbbsReceitas() {
    cbbCategoria.setEnabled(false);
    cbbReceita.setEnabled(false);
    }

    private void btmStartSet() {
     btmAlterar.setEnabled(false);
     btmCancelar.setEnabled(false);
     btmNovo.setEnabled(false);
     btmRemover.setEnabled(false);
     btmSalvar.setEnabled(false);
     btmAddReceita.setEnabled(false);
     btmRemoveReceita.setEnabled(false);
    
    }

    private void StartSet() throws SQLException {
    
        limparCampos();
        listarCbbQuartos();
    
        btmStartSet();
    
    }
}
